 QUICK_REFERENCE_SUBJECTS = {
    "Biology": [
        ("Cell theory", "All living things are made of cells; cells are the basic unit of life, and cells arise from pre-existing cells."),
        ("Prokaryotic and eukaryotic cells", "Prokaryotes lack a membrane-bound nucleus; eukaryotes have a nucleus and membrane-bound organelles."),
        ("Plasma membrane", "A selectively permeable phospholipid bilayer regulates transport and communication with the environment."),
        ("Diffusion", "Net movement of particles from higher to lower concentration; no cellular energy is required."),
        ("Osmosis", "Diffusion of water across a selectively permeable membrane toward the side with higher effective solute concentration."),
        ("Active transport", "Movement against an electrochemical gradient using energy, commonly from ATP or coupled ion movement."),
        ("Cellular respiration", "Overall aerobic summary: C6H12O6 + 6 O2 -> 6 CO2 + 6 H2O + energy captured in ATP."),
        ("Photosynthesis", "Overall summary: 6 CO2 + 6 H2O + light energy -> C6H12O6 + 6 O2."),
        ("Enzymes", "Biological catalysts lower activation energy; their activity depends on conditions such as temperature, pH, and substrate concentration."),
        ("DNA structure", "DNA is an antiparallel double helix with complementary base pairing: A with T, and C with G."),
        ("Central dogma", "Information generally flows from DNA to RNA by transcription and from RNA to protein by translation."),
        ("Mitosis", "Nuclear division that typically produces two genetically similar daughter cells for growth and repair."),
        ("Meiosis", "Two rounds of cell division produce haploid gametes and increase genetic variation through recombination and independent assortment."),
        ("Mendelian segregation", "The two alleles for a gene separate during gamete formation; each gamete receives one allele."),
        ("Hardy-Weinberg equilibrium", "For two alleles: p + q = 1 and p^2 + 2pq + q^2 = 1 under ideal population assumptions."),
        ("Natural selection", "Heritable traits that improve reproductive success tend to become more common across generations."),
        ("Genetic drift", "Random changes in allele frequencies, especially influential in small populations."),
        ("Ecological energy transfer", "Only a fraction of energy at one trophic level becomes biomass available to the next; energy is lost as heat and through metabolism."),
        ("Population growth", "Exponential model: dN/dt = rN; logistic model: dN/dt = rN(1 - N/K), where K is carrying capacity."),
        ("Scientific method", "Form a testable question, make a prediction, control variables, collect reproducible evidence, and revise explanations when warranted."),
    ],
    "Chemistry": [
        ("Mole and Avogadro's constant", "1 mol contains approximately 6.022 x 10^23 specified particles."),
        ("Molarity", "M = moles of solute / liters of solution."),
        ("Dilution", "For a dilution with conserved solute: M1V1 = M2V2."),
        ("Ideal gas law", "PV = nRT; use a consistent set of units for pressure, volume, and the gas constant R."),
        ("Combined gas law", "For a fixed amount of gas: P1V1/T1 = P2V2/T2, with absolute temperature."),
        ("Density", "Density = mass / volume; common units include g/mL and g/cm^3."),
        ("pH", "pH = -log10[H3O+] for hydronium concentration in mol/L."),
        ("pOH and water", "At 25 C in dilute aqueous solution, pH + pOH = 14.00."),
        ("Stoichiometric ratios", "Balanced-equation coefficients give mole ratios between reactants and products."),
        ("Percent yield", "Percent yield = (actual yield / theoretical yield) x 100%."),
        ("Heat transfer", "q = mcDeltaT, where m is mass, c is specific heat capacity, and DeltaT is the temperature change."),
        ("Enthalpy change", "At constant pressure, q_p = DeltaH for the system; negative DeltaH indicates an exothermic process."),
        ("Gibbs free energy", "DeltaG = DeltaH - TDeltaS; at fixed temperature and pressure, DeltaG < 0 indicates thermodynamic favorability."),
        ("Reaction quotient and equilibrium", "For aA + bB <-> cC + dD, Qc = [C]^c[D]^d / ([A]^a[B]^b); at equilibrium Qc = Kc."),
        ("Le Chatelier's principle", "A system at equilibrium shifts in response to a change in concentration, pressure, or temperature in a direction that partially opposes it."),
        ("Reaction rate law", "A rate law often has form rate = k[A]^m[B]^n; exponents are determined experimentally, not assumed from coefficients."),
        ("First-order half-life", "For a first-order process, t1/2 = ln(2)/k."),
        ("Oxidation numbers", "Oxidation is an increase in oxidation number; reduction is a decrease. Track electron transfer to balance redox reactions."),
        ("Beer-Lambert law", "A = epsilon*l*c, relating absorbance to molar absorptivity, path length, and concentration for suitable conditions."),
        ("Intermolecular forces", "Dispersion, dipole-dipole, and hydrogen-bond attractions help explain trends in boiling point, viscosity, and solubility."),
    ],
    "Computer Science": [
        ("Big-O time complexity", "O(1) is constant, O(log n) logarithmic, O(n) linear, and O(n log n) common for efficient comparison sorting."),
        ("Binary search", "Searches a sorted sequence in O(log n) time by repeatedly halving the remaining search interval."),
        ("Merge sort", "Divide-and-conquer sorting with O(n log n) time and O(n) auxiliary space in its standard array implementation."),
        ("Quick sort", "Partition-based sorting; average time is O(n log n), while the worst case is O(n^2) without safeguards."),
        ("Hash table", "Maps keys to buckets; lookup, insertion, and deletion are average O(1), but can degrade with collisions."),
        ("Stack", "Last-in, first-out structure; push and pop are typically O(1)."),
        ("Queue", "First-in, first-out structure; enqueue and dequeue are typically O(1) with an appropriate implementation."),
        ("Breadth-first search", "Explores a graph by layers; runs in O(V + E) with adjacency lists and finds shortest paths in unweighted graphs."),
        ("Depth-first search", "Explores paths deeply before backtracking; runs in O(V + E) with adjacency lists."),
        ("Dijkstra's algorithm", "Finds single-source shortest paths for nonnegative edge weights; a binary heap implementation is commonly O((V + E) log V)."),
        ("Binary tree traversal", "Preorder visits node-left-right; inorder visits left-node-right; postorder visits left-right-node."),
        ("Recurrence relation", "Describes a recursive algorithm's cost, such as T(n) = 2T(n/2) + O(n) for merge sort."),
        ("Boolean logic", "AND is true only when both inputs are true; OR is true when at least one is true; NOT reverses a truth value."),
        ("Binary place values", "An unsigned bit string b_(k-1)...b_0 represents the sum of b_i * 2^i."),
        ("Relational database keys", "A primary key uniquely identifies a row; a foreign key references a key in another table."),
        ("Database normalization", "Normalization organizes relational data to reduce duplication and update anomalies while preserving relationships."),
        ("SQL selection", "SELECT columns FROM table WHERE condition filters rows; parameterized queries help keep user data separate from SQL code."),
        ("HTTP request-response", "Clients send requests with a method and resource; servers respond with a status code, headers, and often a body."),
        ("REST resource design", "REST-style APIs expose resources through consistent URLs and use HTTP methods with predictable semantics."),
        ("TCP/IP layers", "Internet communication is commonly described through link, internet, transport, and application layers."),
    ],
    "Economics": [
        ("Opportunity cost", "The value of the next-best alternative given up when a choice is made."),
        ("Demand", "Quantity demanded generally falls as price rises, holding other influences constant; this is a movement along a demand curve."),
        ("Supply", "Quantity supplied generally rises as price rises, holding other influences constant; this is a movement along a supply curve."),
        ("Market equilibrium", "Equilibrium occurs where quantity demanded equals quantity supplied; shifts in either curve change the equilibrium."),
        ("Price elasticity of demand", "Ed = percentage change in quantity demanded / percentage change in price; the absolute value measures responsiveness."),
        ("Cross-price elasticity", "Exy = percentage change in quantity demanded of X / percentage change in price of Y; sign helps indicate substitutes or complements."),
        ("Income elasticity", "Ey = percentage change in quantity demanded / percentage change in income; sign and size describe how demand responds to income."),
        ("Total revenue", "TR = price x quantity sold."),
        ("Profit", "Economic profit = total revenue - explicit costs - opportunity costs of owned resources."),
        ("Marginal analysis", "Choose an action while its marginal benefit exceeds its marginal cost; the efficient margin is where MB = MC."),
        ("GDP expenditure identity", "GDP = C + I + G + (X - M): consumption, investment, government purchases, and net exports."),
        ("Real and nominal GDP", "Real GDP adjusts output for price changes; nominal GDP values current output at current prices."),
        ("GDP deflator", "GDP deflator = (nominal GDP / real GDP) x 100, using the same base-year convention."),
        ("Inflation rate", "Inflation rate = ((price index this period - price index prior period) / price index prior period) x 100%."),
        ("Unemployment rate", "Unemployment rate = unemployed people actively seeking work / labor force x 100%."),
        ("Labor force participation", "Participation rate = labor force / working-age population x 100%."),
        ("Simple multiplier model", "In a simplified model, spending multiplier = 1 / (1 - MPC), where MPC is the marginal propensity to consume."),
        ("Comparative advantage", "A producer has comparative advantage in a good when its opportunity cost of producing that good is lower."),
        ("Monetary policy", "Central banks influence financial conditions using tools such as policy interest rates and asset operations to support their mandates."),
        ("Fiscal policy", "Government spending and taxation affect aggregate demand, distribution, and public finances; effects depend on economic conditions and policy design."),
    ],
    "English": [
        ("Thesis and central claim", "A thesis makes a focused, debatable claim and signals the reasoning a paper will develop."),
        ("Close reading", "Analyze specific choices in diction, imagery, syntax, structure, and tone using textual evidence."),
        ("Rhetorical situation", "Consider author, audience, purpose, context, genre, and constraints when interpreting or composing a text."),
        ("Ethos, pathos, and logos", "Ethos concerns credibility, pathos emotional appeal, and logos reasoning; effective arguments often combine them."),
        ("Claim, evidence, warrant", "A claim states a point, evidence supports it, and a warrant explains why that evidence supports the claim."),
        ("Counterargument", "Represent a meaningful opposing view fairly, then respond with evidence and reasoning rather than dismissing it."),
        ("Paragraph structure", "A focused paragraph advances one purpose, integrates relevant evidence, explains it, and connects to the larger argument."),
        ("Quotation integration", "Introduce quotations, provide necessary context, cite accurately, and explain their significance in your own words."),
        ("Primary and secondary sources", "Primary sources provide direct material from a subject or period; secondary sources interpret or analyze evidence."),
        ("Source evaluation", "Assess an author's expertise, evidence, publication process, purpose, date, and limitations for the question at hand."),
        ("Paraphrase and summary", "A paraphrase restates a specific passage in new wording; a summary condenses the main ideas of a larger work."),
        ("Citation and attribution", "Cite quotations, paraphrases, data, and borrowed ideas using a consistent style so readers can locate sources."),
        ("Comma splice", "Two independent clauses need a period, semicolon, or coordinating conjunction rather than a comma alone."),
        ("Active and passive voice", "Active voice foregrounds the actor; passive voice foregrounds the receiver or result and can be useful when the actor is unknown or secondary."),
        ("Sentence variety", "Vary sentence length and structure purposefully while keeping relationships among ideas clear."),
        ("Revision versus proofreading", "Revision improves ideas, evidence, and organization; proofreading checks sentence-level correctness and formatting."),
        ("Literary point of view", "First-, second-, and third-person narration shape access to events, reliability, and reader perspective."),
        ("Figurative language", "Metaphor, simile, personification, and related devices create associations that extend beyond literal meaning."),
        ("Tone and mood", "Tone is the writer or speaker's attitude; mood is the atmosphere experienced by a reader."),
        ("Genre and audience", "Genre conventions and audience expectations shape structure, evidence, style, and the choices a writer makes."),
    ],
    "History": [
        ("Primary-source analysis", "Identify creator, date, audience, purpose, point of view, and limits before using a source as evidence."),
        ("Contextualization", "Connect an event or source to the wider social, political, economic, and cultural conditions of its time."),
        ("Historical causation", "Distinguish long-term conditions, short-term triggers, and contributing causes; avoid treating one cause as sufficient without evidence."),
        ("Continuity and change", "Compare what changed and what persisted across a defined period, place, and group."),
        ("Chronology and periodization", "Use timelines to establish sequence, while recognizing that historical periods are interpretive frameworks."),
        ("Historical significance", "Evaluate significance by considering scale, duration, consequences, and meaning to different groups."),
        ("Corroboration", "Compare independent sources for agreement, disagreement, shared origins, and gaps in evidence."),
        ("Historical argument", "Make a defensible claim, support it with specific evidence, and explain how the evidence establishes the claim."),
        ("Empire and state formation", "Study how states consolidate authority, administer territory, and interact with neighboring peoples."),
        ("Trade and exchange", "Trace how goods, technologies, people, and ideas move through networks and reshape societies."),
        ("Migration and diaspora", "Analyze reasons for movement, routes, reception, and effects on both sending and receiving communities."),
        ("Religion and belief", "Examine how beliefs and institutions influence identity, culture, politics, and everyday life in varied contexts."),
        ("Revolution and reform", "Compare the conditions, participants, ideas, strategies, and outcomes of movements for political or social change."),
        ("Industrialization", "Explore how mechanized production transformed labor, cities, economies, environments, and social relationships."),
        ("Colonialism and decolonization", "Study systems of foreign control, local responses, independence movements, and enduring legacies."),
        ("Nationalism", "Analyze how shared identity and political claims contribute to state-building, solidarity, conflict, or exclusion."),
        ("War and society", "Investigate causes and consequences of conflict for civilians, institutions, economies, and international relations."),
        ("Historical geography", "Use maps and spatial evidence to understand how environment, borders, resources, and location shaped events."),
        ("Oral history", "Treat recorded testimony as evidence shaped by memory, interview context, later interpretation, and the narrator's perspective."),
        ("Ethical use of evidence", "Represent people and communities carefully, distinguish evidence from inference, and acknowledge uncertainty and contested interpretations."),
    ],
    "Mathematics": [
        ("Slope-intercept form", "For a line, y = mx + b, where m is slope and b is the vertical intercept."),
        ("Slope between two points", "m = (y2 - y1) / (x2 - x1), when x2 != x1."),
        ("Distance formula", "Distance between (x1,y1) and (x2,y2): d = sqrt((x2-x1)^2 + (y2-y1)^2)."),
        ("Midpoint formula", "Midpoint of two points: ((x1+x2)/2, (y1+y2)/2)."),
        ("Quadratic formula", "For ax^2 + bx + c = 0, x = (-b +/- sqrt(b^2 - 4ac)) / (2a), with a != 0."),
        ("Exponent product rule", "For matching bases: a^m * a^n = a^(m+n)."),
        ("Exponent quotient rule", "For a != 0: a^m / a^n = a^(m-n)."),
        ("Logarithm product rule", "log_b(xy) = log_b(x) + log_b(y), for positive x,y and valid base b."),
        ("Compound interest", "A = P(1 + r/n)^(nt) for nominal annual rate r compounded n times per year over t years."),
        ("Arithmetic series", "Sum of n terms: S_n = n(a_1 + a_n)/2."),
        ("Geometric series", "For common ratio r != 1: S_n = a_1(1-r^n)/(1-r)."),
        ("Pythagorean theorem", "For a right triangle with legs a,b and hypotenuse c: a^2 + b^2 = c^2."),
        ("Circle area and circumference", "Area A = pi*r^2; circumference C = 2*pi*r."),
        ("Triangle area", "A = (1/2)bh, where b is a base and h is its perpendicular height."),
        ("Sine and cosine", "In a right triangle, sin(theta) = opposite/hypotenuse and cos(theta) = adjacent/hypotenuse."),
        ("Fundamental trigonometric identity", "sin^2(theta) + cos^2(theta) = 1."),
        ("Derivative power rule", "d/dx[x^n] = n*x^(n-1), where the power rule applies."),
        ("Product rule", "If y = f(x)g(x), then y' = f'g + fg'."),
        ("Chain rule", "If y = f(g(x)), then y' = f'(g(x))*g'(x)."),
        ("Definite integral and accumulation", "The definite integral from a to b accumulates signed area; if F' = f, then integral_a^b f(x)dx = F(b)-F(a)."),
    ],
    "Physics": [
        ("Average velocity", "v_avg = Delta x / Delta t; displacement is directional, unlike total distance."),
        ("Constant-acceleration position", "x = x0 + v0*t + (1/2)*a*t^2 for constant acceleration."),
        ("Constant-acceleration velocity", "v = v0 + a*t for constant acceleration."),
        ("Newton's second law", "Net force F_net = m*a."),
        ("Weight near Earth's surface", "Weight magnitude W = m*g, where g is approximately 9.81 m/s^2 near Earth's surface."),
        ("Momentum", "Linear momentum p = m*v."),
        ("Impulse-momentum theorem", "Impulse J = F_avg*Delta t = Delta p."),
        ("Kinetic energy", "K = (1/2)*m*v^2."),
        ("Gravitational potential energy", "Near Earth's surface, U_g = m*g*h relative to a chosen reference height."),
        ("Work by a constant force", "W = F*d*cos(theta), where theta is the angle between force and displacement."),
        ("Power", "Average power P = W/Delta t; for constant force and velocity, P = F dot v."),
        ("Hooke's law", "For an ideal spring, F = -k*x, with displacement x measured from equilibrium."),
        ("Wave speed", "v = f*lambda, where f is frequency and lambda is wavelength."),
        ("Period and frequency", "f = 1/T for a periodic process."),
        ("Ohm's law", "V = I*R for an ohmic component under conditions where resistance is constant."),
        ("Electric power", "P = I*V; for an ohmic resistor, P = I^2*R = V^2/R."),
        ("Coulomb's law", "Force magnitude between point charges: F = k*|q1*q2|/r^2 in vacuum."),
        ("Density", "rho = m/V."),
        ("Specific heat", "For no phase change, Q = m*c*DeltaT."),
        ("Ideal gas law", "P*V = n*R*T, with absolute temperature and consistent units."),
    ],
    "Statistics": [
        ("Arithmetic mean", "x_bar = (sum of observations)/n; sensitive to extreme values."),
        ("Sample variance", "s^2 = sum((x_i - x_bar)^2)/(n - 1) for a sample."),
        ("Sample standard deviation", "s = sqrt(s^2); describes spread in the original measurement units."),
        ("Range", "Range = maximum value - minimum value; depends only on the two extremes."),
        ("Interquartile range", "IQR = Q3 - Q1; spread of the middle half of ordered observations."),
        ("z-score", "z = (x - mean)/standard deviation; expresses distance from the mean in standard-deviation units."),
        ("Standard error of the mean", "SE(x_bar) = s/sqrt(n), under the usual independent-sampling setup."),
        ("Confidence interval for a mean", "A common form is estimate +/- critical value * standard error; the method's assumptions matter."),
        ("Probability complement", "P(not A) = 1 - P(A)."),
        ("Addition rule", "P(A or B) = P(A) + P(B) - P(A and B)."),
        ("Conditional probability", "P(A given B) = P(A and B)/P(B), when P(B) > 0."),
        ("Independent events", "If A and B are independent, P(A and B) = P(A)*P(B)."),
        ("Bayes' theorem", "P(A given B) = P(B given A)*P(A)/P(B), when P(B) > 0."),
        ("Binomial probability", "P(X=k) = C(n,k)*p^k*(1-p)^(n-k) for a binomial model's assumptions."),
        ("Expected value", "For a discrete variable, E(X) = sum(x * P(X=x))."),
        ("Correlation coefficient", "Pearson r measures linear association and ranges from -1 to 1; correlation alone does not establish causation."),
        ("Least-squares regression line", "Predicted response often has form y_hat = b0 + b1*x; residual = observed y - predicted y."),
        ("Coefficient of determination", "R^2 describes the proportion of observed response variation accounted for by a fitted model in context."),
        ("Central limit theorem", "Under suitable conditions, the sampling distribution of a mean becomes approximately normal as sample size grows."),
        ("P-value", "A p-value is the probability, under the null model and assumptions, of data at least as incompatible with that model as observed."),
    ],
    "Study Skills": [
        ("Active recall", "Retrieve information from memory before checking notes; use blank-page summaries, flashcards, or self-quizzing."),
        ("Spaced practice", "Revisit material over multiple sessions rather than cramming in one sitting; space reviews as recall becomes more reliable."),
        ("Interleaving", "Mix related problem types or topics so you practice identifying which method applies, not only repeating one procedure."),
        ("Elaboration", "Explain why an idea is true and connect it to examples, prior knowledge, or contrasting cases."),
        ("Self-explanation", "Talk through each step of a solution and identify why the step is valid, not just what the step is."),
        ("Dual coding", "Pair concise verbal explanations with meaningful diagrams, timelines, or models; keep both representations aligned."),
        ("Practice testing", "Use low-stakes quizzes to expose gaps and strengthen retrieval; correct errors with feedback."),
        ("Feynman-style explanation", "Explain a concept in plain language, notice gaps, revisit the source, and refine the explanation."),
        ("Pomodoro-style focus blocks", "Try a focused work interval followed by a short break, then adjust interval length to the task and your attention."),
        ("SMART goals", "Make goals specific, measurable, achievable, relevant, and time-bound; define a next action you can complete."),
        ("Time blocking", "Reserve calendar blocks for defined tasks and include realistic transitions and breaks."),
        ("Task prioritization", "Rank tasks by importance, deadline, effort, and dependencies; break large tasks into visible next steps."),
        ("Cornell notes", "Organize notes into a main-note area, cue or question column, and short summary; revisit them through recall."),
        ("Concept mapping", "Draw concepts as nodes and label connections with meaningful relationships rather than only grouping keywords."),
        ("Reading with questions", "Preview headings, turn them into questions, read for answers, and summarize without looking at the text."),
        ("Error log", "Record a mistake, its cause, the correct reasoning, and a similar problem to retry later."),
        ("Metacognitive check", "Before and after studying, predict what you can do, test yourself, and compare confidence with actual performance."),
        ("Study environment", "Reduce avoidable distractions, prepare materials, and choose a place that supports the kind of work you need to do."),
        ("Sleep and learning", "Consistent adequate sleep supports attention and memory; plan study sessions so learning is not routinely displaced by sleep."),
        ("Weekly review", "Review deadlines, notes, quiz errors, and progress once a week, then adjust the next week's plan."),
    ],
}
